export default {
    primary: '#000000',
    secondary: '#ff7f00',
    iconColor: '#33d3ee',
    danger: '',
    success: '',
    circle: '#eae8e9',
    drawer: '#fafafa',
    drawerImage: '#bdbdbd',
    drawerTop: '#838383',
    drawerDown: '#cccacb',
    background: '#ababab',
    activeTintColor: '#048a9d',
    inactiveTintColor: '#000000',
}